# Generated by Django 4.0.1 on 2022-01-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
