# Generated by Django 4.0.2 on 2022-02-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('map_url', models.CharField(max_length=200)),
                ('img_url', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('has_sockets', models.BooleanField()),
                ('has_toilet', models.BooleanField()),
                ('has_wifi', models.BooleanField()),
                ('can_take_calls', models.BooleanField()),
                ('seats', models.CharField(max_length=200)),
                ('coffee_price', models.CharField(max_length=200)),
            ],
        ),
    ]
