# Generated by Django 4.0.2 on 2022-02-05 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cafe',
            table='cafes',
        ),
    ]
