# Generated by Django 4.0.2 on 2022-02-05 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_cafe_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cafe',
            table=None,
        ),
    ]
